### PR TITLE
Rattler

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
@wolfv follow up question: is it possible to disable `pip check`?

**Comment by wolfv** [comment]
Yes, you can say pip_check: false :)

**Comment by looooo** [comment]
big thanks @wolfv . Pixi and rattler-build are such great tools. Love it.
wow `conda smithy rerender` is so much faster. The logs are way prettier. This is such a big improvement. Keep on the good work. Whats the best way to support the pixi-related projects in form of donations?

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
