### PR TITLE
Cpp 2

### PR DESCRIPTION
**Pull request by hiaselhans**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hiaselhans** [comment]
@looooo des kompiliert mal so... weisst du wie man die python versionen einschränken kannn? (>3.6)

:)

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by hiaselhans** [comment]
@conda-forge-admin, please rerender

**Comment by hiaselhans** [comment]
danke @looooo !

jetzt müsst ma den build nomal auslösen. wie am besten?

**Comment by looooo** [comment]
@conda-forge-admin, please restart ci

@hiaselhans das ist ganz einfach ; )

**Comment by looooo** [comment]
https://conda-forge.org/docs/maintainer/00_intro.html

**Pull request closed without merging**
